### ISSUE TITLE
How to Run

### ISSUE THREAD

**Issue by areef5** [paduchurikowsik/ionic4-firebase-PhoneAuth#2]
Please tell me how to run this project in Android??
What are the necessary tools i have to install?

**Comment by paduchurikowsik** [comment]
@areef5 you can find the installation guide on [Ionic Website](https://ionicframework.com/ ) or you can find the details [here](https://ionicframework.com/docs/installation/android), [here](https://ionicframework.com/docs/building/android) and [here](https://ionicframework.com/docs/publishing/play-store). 

Please have a look at the documentation information on the site for installations and running on android.
